### ISSUE TITLE
How to return multiple rows

### ISSUE THREAD

**Issue by laoshanxi** [tcolgate/grafana-simple-json-go#1]
I saw this function return all the query data to Grafana, but the demo only have one row, I saw those are only columns, how to return 2 rows data?

https://github.com/tcolgate/grafana-simple-json-go/blob/c8fe67d85e9477295830c767b5defed31c9baf2c/simplejson_example_test.go#L27

**Comment by laoshanxi** [comment]
so just continue append() value to the column data should be OK?

https://github.com/tcolgate/jaeger-simplejson/blob/4bf3dbfa4e5d93ca2336aedbaf95fb6648cc5402/main.go#L203

**Comment by tcolgate** [comment]
yes, sorry, not well documented. Data is all the rows of data for that column. All the columns should end up with the same number of Data items (one for each row of the complete table.
I've not updated this package properly for a while, I know they've made some small changes to the API.

**Comment by laoshanxi** [comment]
Got it, thanks for the usefull tool.
